services:
  app:
    image: prepaid_monitor
    build:
      context: .
      target: production
    container_name: prepaid_monitor
    env_file:
      - .env
    volumes:
      - ${HOME}/logs:/usr/prod/ppol/logs
      - ${HOME}/plsd-admin:/usr/prod/ppol/plsd-admin
      - ${HOME}/sys-utils/conf:/usr/prod/ppol/sys-utils/conf
      - /tmp:/tmp
