services:
  app:
    image: prepaid_monitor
    build: 
      context: .
      target: prod
    container_name: prepaid_monitor
    env_file:
      - .env
    volumes: 
      - /Users/don/logs:/usr/prod/ppol/logs
      - /Users/don/plsd-admin:/usr/prod/ppol/plsd-admin
      - /Users/don/sys-utils://usr/prod/ppol/sys-utils
      - /tmp:/tmp

